### ISSUE TITLE
keyword input suggestion

### ISSUE THREAD

**Issue by steuerzentrale** [MariusLang/node-red-contrib-feiertage-switzerland#11]
**Is your feature request related to a problem?**
No, it could be an enhancement.

**Describe the solution you'd like**
As of now you can input **isTodayHoliday**. It would be great if you can input is**Tomorrow**Holiday in order to use it for automations.

**Describe alternatives you've considered**

**Additional context**

**Comment by MariusLang** [comment]
A new version of **node-red-contrib-feiertage-switzerland** is going to be released in the next days.
You're feature is implemented in the new version!
